name = "ai-workplace-history"
main = "dist/historyWorker.js"
compatibility_date = "2023-05-18"

[vars]
ENVIRONMENT = "production"

[[r2_buckets]]
binding = "HISTORY_BUCKET"
bucket_name = "ai-workplace-history"
